"""Removed name from Recipe, as its always the workpieces name

Revision ID: 042357e55395
Revises: 08fcd8c81638
Create Date: 2025-09-24 15:48:57.135560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '042357e55395'
down_revision: Union[str, None] = '08fcd8c81638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_name'), table_name='recipe')
    op.drop_constraint(op.f('recipe_name_workpiece_id_machine_id_key'), 'recipe', type_='unique')
    op.create_unique_constraint(None, 'recipe', ['workpiece_id', 'machine_id'])
    op.drop_column('recipe', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'recipe', type_='unique')
    op.create_unique_constraint(op.f('recipe_name_workpiece_id_machine_id_key'), 'recipe', ['name', 'workpiece_id', 'machine_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_recipe_name'), 'recipe', ['name'], unique=False)
    # ### end Alembic commands ###
