"""reinit_database_schema

Revision ID: 08fcd8c81638
Revises: 
Create Date: 2025-09-24 09:23:18.849003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08fcd8c81638'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine', sa.Column('burden_rate', sa.Integer(), nullable=False, server_default='100'))
    op.add_column('toollife', sa.Column('cycle_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('toollife', 'cycle_time')
    op.drop_column('machine', 'burden_rate')
    # ### end Alembic commands ###
