"""Added price to tool

Revision ID: 0c6aed9f25ee
Revises: 8d27924548ec
Create Date: 2025-03-13 10:02:09.327173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c6aed9f25ee'
down_revision: Union[str, None] = '8d27924548ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('price', sa.Numeric(), nullable=False, server_default=sa.text('0.0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool', 'price')
    # ### end Alembic commands ###
