"""Added shifts

Revision ID: 0dcec4bfb26f
Revises: 31c1439a161f
Create Date: 2025-02-20 13:08:03.264274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0dcec4bfb26f'
down_revision: Union[str, None] = '31c1439a161f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('number')
    )
    op.add_column('user', sa.Column('payment_type', sa.Enum('HOURLY', 'SALARY', name='paymenttype'), nullable=False, server_default='HOURLY'))
    op.add_column('user', sa.Column('shift_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_user_shift_id', 'user', 'shift', ['shift_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_shift_id', 'user', type_='foreignkey')
    op.drop_column('user', 'shift_id')
    op.drop_column('user', 'payment_type')
    op.drop_table('shift')
    # ### end Alembic commands ###
