"""renamed created_by to creator_id in toolLife

Revision ID: 14f078cdcb77
Revises: 25caad939588
Create Date: 2025-03-21 09:29:49.897667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f078cdcb77'
down_revision: Union[str, None] = '25caad939588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toollife', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.execute("UPDATE toollife SET creator_id = created_by")
    op.drop_constraint('toollife_created_by_fkey', 'toollife', type_='foreignkey')
    op.create_foreign_key(None, 'toollife', 'user', ['creator_id'], ['id'], ondelete='SET NULL')
    op.drop_column('toollife', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toollife', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.execute("UPDATE toollife SET created_by = creator_id")
    op.drop_constraint(None, 'toollife', type_='foreignkey')
    op.create_foreign_key('toollife_created_by_fkey', 'toollife', 'user', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_column('toollife', 'creator_id')
    # ### end Alembic commands ###
