"""refined uniqueness of machine based on name and line id

Revision ID: 1acd1b671f67
Revises: 432181151ef5
Create Date: 2025-06-23 09:52:18.066870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1acd1b671f67'
down_revision: Union[str, None] = '432181151ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machine_name'), table_name='machine')
    op.create_index(op.f('ix_machine_name'), 'machine', ['name'], unique=False)
    op.create_unique_constraint(None, 'machine', ['name', 'line_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'machine', type_='unique')
    op.drop_index(op.f('ix_machine_name'), table_name='machine')
    op.create_index(op.f('ix_machine_name'), 'machine', ['name'], unique=True)
    # ### end Alembic commands ###
