"""Added unique constraints to order delivery

Revision ID: 25caad939588
Revises: bfffcd32703c
Create Date: 2025-03-17 14:11:54.405951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25caad939588'
down_revision: Union[str, None] = 'bfffcd32703c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'orderdelivery', ['order_id', 'delivery_date', 'quantity'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orderdelivery', type_='unique')
    # ### end Alembic commands ###
