"""Added Production model for tracking of hourly production

Revision ID: 265a24829e8f
Revises: add_machine_status_notify
Create Date: 2025-04-24 09:04:55.337626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '265a24829e8f'
down_revision: Union[str, None] = 'add_machine_status_notify'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('workpiece_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('finished', sa.Integer(), nullable=False),
    sa.Column('started', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['line.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workpiece_id'], ['workpiece.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_date'), 'production', ['date'], unique=False)
    op.create_index(op.f('ix_production_workpiece_id'), 'production', ['workpiece_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_workpiece_id'), table_name='production')
    op.drop_index(op.f('ix_production_date'), table_name='production')
    op.drop_table('production')
    # ### end Alembic commands ###
