"""added shipping company and tracking number to toolorder

Revision ID: 31c1439a161f
Revises: 705fc7673f10
Create Date: 2025-02-20 07:59:56.652199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '31c1439a161f'
down_revision: Union[str, None] = '705fc7673f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toolorder', sa.Column('tracking_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('toolorder', sa.Column('shipping_company', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('toolorder', 'shipping_company')
    op.drop_column('toolorder', 'tracking_number')
    # ### end Alembic commands ###
