"""added minimum tool life to toolPosition

Revision ID: 432181151ef5
Revises: 9becbc263bfc
Create Date: 2025-06-03 13:36:29.629429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '432181151ef5'
down_revision: Union[str, None] = '5db1068998a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toolposition', sa.Column('min_life', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('toolposition', 'min_life')
    # ### end Alembic commands ###
