"""Added Line model

Revision ID: 44d0460f72ac
Revises: 6cb74dcf30c3
Create Date: 2025-03-11 09:26:00.995845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '44d0460f72ac'
down_revision: Union[str, None] = '6cb74dcf30c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line',
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_line_name'), 'line', ['name'], unique=True)
    op.add_column('machine', sa.Column('line_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'machine', 'line', ['line_id'], ['id'], ondelete='SET NULL')
    op.add_column('workpiece', sa.Column('line_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workpiece', 'line', ['line_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workpiece', type_='foreignkey')
    op.drop_column('workpiece', 'line_id')
    op.drop_constraint(None, 'machine', type_='foreignkey')
    op.drop_column('machine', 'line_id')
    op.drop_index(op.f('ix_line_name'), table_name='line')
    op.drop_table('line')
    # ### end Alembic commands ###
