"""Updated ToolOrders

Revision ID: 50570acd3037
Revises: ce72a2ad7a0b
Create Date: 2025-02-17 10:08:02.180098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50570acd3037'
down_revision: Union[str, None] = 'ce72a2ad7a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('toolorder', 'remaining_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toolorder', sa.Column('remaining_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
