"""removed final part from recipe

Revision ID: 59b9fa487567
Revises: 30ef50c5b387
Create Date: 2025-01-09 12:16:25.637477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59b9fa487567'
down_revision: Union[str, None] = '30ef50c5b387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recipe_final_part', table_name='recipe')
    op.drop_column('recipe', 'final_part')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('final_part', sa.VARCHAR(), server_default=sa.text("'--'::character varying"), autoincrement=False, nullable=False))
    op.create_index('ix_recipe_final_part', 'recipe', ['final_part'], unique=False)
    # ### end Alembic commands ###
