"""made toolConsumption number optional and dropped indexation (was replaced my tool_id and datetime uniqueness)

Revision ID: 5db1068998a6
Revises: 6cd25c5e32f4
Create Date: 2025-05-19 12:56:12.097459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5db1068998a6'
down_revision: Union[str, None] = '6cd25c5e32f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('toolconsumption', 'number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_toolconsumption_number', table_name='toolconsumption')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_toolconsumption_number', 'toolconsumption', ['number'], unique=True)
    op.alter_column('toolconsumption', 'number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
