"""added number (str) to user for identification through cribmaster

Revision ID: 669a6061ef22
Revises: daff7ce14839
Create Date: 2025-01-29 14:54:19.840985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '669a6061ef22'
down_revision: Union[str, None] = 'daff7ce14839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'number')
    # ### end Alembic commands ###
