"""add unique constraint to tool_consumption

Revision ID: 6cd25c5e32f4
Revises: 6f39425090b4
Create Date: 2025-05-19 12:30:11.993003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cd25c5e32f4'
down_revision: Union[str, None] = '6f39425090b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DELETE FROM toolconsumption a
        USING toolconsumption b
        WHERE a.id > b.id
          AND a.tool_id = b.tool_id
          AND a.datetime = b.datetime;
    """)
    op.create_unique_constraint('uq_toolconsumption_tool_id_datetime', 'toolconsumption', ['tool_id', 'datetime'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_toolconsumption_tool_id_datetime', 'toolconsumption', type_='unique')
    # ### end Alembic commands ###
