"""specified on delete relationships

Revision ID: 6d7c6d3e41ee
Revises: ce1c424bfca9
Create Date: 2025-02-28 11:55:24.472092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d7c6d3e41ee'
down_revision: Union[str, None] = 'ce1c424bfca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('changeover_recipe_id_fkey', 'changeover', type_='foreignkey')
    op.drop_constraint('changeover_machine_id_fkey', 'changeover', type_='foreignkey')
    op.drop_constraint('changeover_performed_by_fkey', 'changeover', type_='foreignkey')
    op.create_foreign_key(None, 'changeover', 'user', ['performed_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'changeover', 'machine', ['machine_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'changeover', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('heartbeat_log_device_id_fkey', 'heartbeat', type_='foreignkey')
    op.create_foreign_key(None, 'heartbeat', 'logdevice', ['log_device_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('machine_current_recipe_id_fkey', 'machine', type_='foreignkey')
    op.drop_constraint('machine_log_device_id_fkey', 'machine', type_='foreignkey')
    op.create_foreign_key(None, 'machine', 'logdevice', ['log_device_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'machine', 'recipe', ['current_recipe_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('orderdelivery_order_id_fkey', 'orderdelivery', type_='foreignkey')
    op.create_foreign_key(None, 'orderdelivery', 'toolorder', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('recipe_machine_id_fkey', 'recipe', type_='foreignkey')
    op.drop_constraint('recipe_workpiece_id_fkey', 'recipe', type_='foreignkey')
    op.create_foreign_key(None, 'recipe', 'machine', ['machine_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recipe', 'workpiece', ['workpiece_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('toolattributevalue_tool_attribute_id_fkey', 'toolattributevalue', type_='foreignkey')
    op.drop_constraint('toolattributevalue_tool_id_fkey', 'toolattributevalue', type_='foreignkey')
    op.create_foreign_key(None, 'toolattributevalue', 'tool', ['tool_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'toolattributevalue', 'toolattribute', ['tool_attribute_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('toolconsumption_tool_position_id_fkey', 'toolconsumption', type_='foreignkey')
    op.drop_constraint('toolconsumption_tool_id_fkey', 'toolconsumption', type_='foreignkey')
    op.drop_constraint('toolconsumption_user_id_fkey', 'toolconsumption', type_='foreignkey')
    op.drop_constraint('toolconsumption_workpiece_id_fkey', 'toolconsumption', type_='foreignkey')
    op.drop_constraint('toolconsumption_recipe_id_fkey', 'toolconsumption', type_='foreignkey')
    op.drop_constraint('toolconsumption_machine_id_fkey', 'toolconsumption', type_='foreignkey')
    op.create_foreign_key(None, 'toolconsumption', 'toolposition', ['tool_position_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'toolconsumption', 'machine', ['machine_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'toolconsumption', 'workpiece', ['workpiece_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'toolconsumption', 'tool', ['tool_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'toolconsumption', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'toolconsumption', 'recipe', ['recipe_id'], ['id'], ondelete='SET NULL')
    op.alter_column('toollife', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('toollife', 'machine_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('toollife', 'recipe_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('toollife', 'change_reason_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('toollife', 'tool_position_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('toollife_created_by_fkey', 'toollife', type_='foreignkey')
    op.drop_constraint('toollife_tool_id_fkey', 'toollife', type_='foreignkey')
    op.drop_constraint('toollife_recipe_id_fkey', 'toollife', type_='foreignkey')
    op.drop_constraint('toollife_machine_id_fkey', 'toollife', type_='foreignkey')
    op.drop_constraint('toollife_change_reason_id_fkey', 'toollife', type_='foreignkey')
    op.drop_constraint('toollife_tool_position_id_fkey', 'toollife', type_='foreignkey')
    op.create_foreign_key(None, 'toollife', 'toolposition', ['tool_position_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'toollife', 'changereason', ['change_reason_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'toollife', 'recipe', ['recipe_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'toollife', 'machine', ['machine_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'toollife', 'user', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'toollife', 'tool', ['tool_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('toolorder_user_id_fkey', 'toolorder', type_='foreignkey')
    op.create_foreign_key(None, 'toolorder', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('toolposition', 'tool_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('toolposition_tool_id_fkey', 'toolposition', type_='foreignkey')
    op.create_foreign_key(None, 'toolposition', 'tool', ['tool_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_user_shift_id', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'shift', ['shift_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('fk_user_shift_id', 'user', 'shift', ['shift_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'toolposition', type_='foreignkey')
    op.create_foreign_key('toolposition_tool_id_fkey', 'toolposition', 'tool', ['tool_id'], ['id'])
    op.alter_column('toolposition', 'tool_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'toolorder', type_='foreignkey')
    op.create_foreign_key('toolorder_user_id_fkey', 'toolorder', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'toollife', type_='foreignkey')
    op.drop_constraint(None, 'toollife', type_='foreignkey')
    op.drop_constraint(None, 'toollife', type_='foreignkey')
    op.drop_constraint(None, 'toollife', type_='foreignkey')
    op.drop_constraint(None, 'toollife', type_='foreignkey')
    op.drop_constraint(None, 'toollife', type_='foreignkey')
    op.create_foreign_key('toollife_tool_position_id_fkey', 'toollife', 'toolposition', ['tool_position_id'], ['id'])
    op.create_foreign_key('toollife_change_reason_id_fkey', 'toollife', 'changereason', ['change_reason_id'], ['id'])
    op.create_foreign_key('toollife_machine_id_fkey', 'toollife', 'machine', ['machine_id'], ['id'])
    op.create_foreign_key('toollife_recipe_id_fkey', 'toollife', 'recipe', ['recipe_id'], ['id'])
    op.create_foreign_key('toollife_tool_id_fkey', 'toollife', 'tool', ['tool_id'], ['id'])
    op.create_foreign_key('toollife_created_by_fkey', 'toollife', 'user', ['created_by'], ['id'])
    op.alter_column('toollife', 'tool_position_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('toollife', 'change_reason_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('toollife', 'recipe_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('toollife', 'machine_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('toollife', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'toolconsumption', type_='foreignkey')
    op.drop_constraint(None, 'toolconsumption', type_='foreignkey')
    op.drop_constraint(None, 'toolconsumption', type_='foreignkey')
    op.drop_constraint(None, 'toolconsumption', type_='foreignkey')
    op.drop_constraint(None, 'toolconsumption', type_='foreignkey')
    op.drop_constraint(None, 'toolconsumption', type_='foreignkey')
    op.create_foreign_key('toolconsumption_machine_id_fkey', 'toolconsumption', 'machine', ['machine_id'], ['id'])
    op.create_foreign_key('toolconsumption_recipe_id_fkey', 'toolconsumption', 'recipe', ['recipe_id'], ['id'])
    op.create_foreign_key('toolconsumption_workpiece_id_fkey', 'toolconsumption', 'workpiece', ['workpiece_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('toolconsumption_user_id_fkey', 'toolconsumption', 'user', ['user_id'], ['id'])
    op.create_foreign_key('toolconsumption_tool_id_fkey', 'toolconsumption', 'tool', ['tool_id'], ['id'])
    op.create_foreign_key('toolconsumption_tool_position_id_fkey', 'toolconsumption', 'toolposition', ['tool_position_id'], ['id'])
    op.drop_constraint(None, 'toolattributevalue', type_='foreignkey')
    op.drop_constraint(None, 'toolattributevalue', type_='foreignkey')
    op.create_foreign_key('toolattributevalue_tool_id_fkey', 'toolattributevalue', 'tool', ['tool_id'], ['id'])
    op.create_foreign_key('toolattributevalue_tool_attribute_id_fkey', 'toolattributevalue', 'toolattribute', ['tool_attribute_id'], ['id'])
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.create_foreign_key('recipe_workpiece_id_fkey', 'recipe', 'workpiece', ['workpiece_id'], ['id'])
    op.create_foreign_key('recipe_machine_id_fkey', 'recipe', 'machine', ['machine_id'], ['id'])
    op.drop_constraint(None, 'orderdelivery', type_='foreignkey')
    op.create_foreign_key('orderdelivery_order_id_fkey', 'orderdelivery', 'toolorder', ['order_id'], ['id'])
    op.drop_constraint(None, 'machine', type_='foreignkey')
    op.drop_constraint(None, 'machine', type_='foreignkey')
    op.create_foreign_key('machine_log_device_id_fkey', 'machine', 'logdevice', ['log_device_id'], ['id'])
    op.create_foreign_key('machine_current_recipe_id_fkey', 'machine', 'recipe', ['current_recipe_id'], ['id'])
    op.drop_constraint(None, 'heartbeat', type_='foreignkey')
    op.create_foreign_key('heartbeat_log_device_id_fkey', 'heartbeat', 'logdevice', ['log_device_id'], ['id'])
    op.drop_constraint(None, 'changeover', type_='foreignkey')
    op.drop_constraint(None, 'changeover', type_='foreignkey')
    op.drop_constraint(None, 'changeover', type_='foreignkey')
    op.create_foreign_key('changeover_performed_by_fkey', 'changeover', 'user', ['performed_by'], ['id'])
    op.create_foreign_key('changeover_machine_id_fkey', 'changeover', 'machine', ['machine_id'], ['id'])
    op.create_foreign_key('changeover_recipe_id_fkey', 'changeover', 'recipe', ['recipe_id'], ['id'])
    # ### end Alembic commands ###
