"""dropped manufacturer_name from tool (unneccessary)

Revision ID: 705fc7673f10
Revises: 8a540b5766b4
Create Date: 2025-02-19 08:32:09.062790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '705fc7673f10'
down_revision: Union[str, None] = '8a540b5766b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tool_manufacturer_name_key', 'tool', type_='unique')
    op.drop_column('tool', 'manufacturer_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('manufacturer_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('tool_manufacturer_name_key', 'tool', ['manufacturer_name'])
    # ### end Alembic commands ###
