"""added delivered to toolorder

Revision ID: 8a540b5766b4
Revises: fa26324c1275
Create Date: 2025-02-18 15:35:51.918313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a540b5766b4'
down_revision: Union[str, None] = 'fa26324c1275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toolorder', sa.Column('delivered', sa.Integer(), nullable=True))
    op.execute("UPDATE toolorder SET delivered = 0")
    op.alter_column('toolorder', 'delivered', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('toolorder', 'delivered')
    # ### end Alembic commands ###
