"""Added final part name info to Recipe

Revision ID: 8b799d3e0abc
Revises: aba0ffc689e9
Create Date: 2025-01-08 07:27:46.610972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8b799d3e0abc'
down_revision: Union[str, None] = 'aba0ffc689e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('final_part', sqlmodel.sql.sqltypes.AutoString(), server_default='--', nullable=False))
    op.create_index(op.f('ix_recipe_final_part'), 'recipe', ['final_part'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_final_part'), table_name='recipe')
    op.drop_column('recipe', 'final_part')
    # ### end Alembic commands ###
