"""Added tool count to toolPosition model

Revision ID: 8d27924548ec
Revises: 44d0460f72ac
Create Date: 2025-03-11 15:05:02.985657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d27924548ec'
down_revision: Union[str, None] = '44d0460f72ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toolposition', sa.Column('tool_count', sa.Integer(), nullable=False, server_default=sa.text('1')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('toolposition', 'tool_count')
    # ### end Alembic commands ###
