"""Added Bollean Regrind and integer max_uses to ToolBase

Revision ID: aba0ffc689e9
Revises: 65037492629a
Create Date: 2025-01-07 10:30:58.686396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aba0ffc689e9'
down_revision: Union[str, None] = '65037492629a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('regrind', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tool', sa.Column('max_uses', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool', 'max_uses')
    op.drop_column('tool', 'regrind')
    # ### end Alembic commands ###
