"""Removed CPN number from tool as its a duplicate of number

Revision ID: b316b5ef6a65
Revises: 042357e55395
Create Date: 2025-10-06 10:07:06.562196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b316b5ef6a65'
down_revision: Union[str, None] = '042357e55395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_cpn_number'), table_name='tool')
    op.drop_column('tool', 'cpn_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('cpn_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_tool_cpn_number'), 'tool', ['cpn_number'], unique=True)
    # ### end Alembic commands ###
