"""added tool attributes dict to tool

Revision ID: c0c22c5247ab
Revises: 291c5d689a06
Create Date: 2025-02-25 09:17:36.598421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0c22c5247ab'
down_revision: Union[str, None] = '291c5d689a06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('tool_attributes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool', 'tool_attributes')
    # ### end Alembic commands ###
