"""renamed creator_id to user_id in toolLife

Revision ID: cd60ac2ba3ae
Revises: 14f078cdcb77
Create Date: 2025-03-21 09:45:04.344826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd60ac2ba3ae'
down_revision: Union[str, None] = '14f078cdcb77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toollife', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute("UPDATE toollife SET user_id = creator_id")
    op.drop_constraint('toollife_creator_id_fkey', 'toollife', type_='foreignkey')
    op.create_foreign_key(None, 'toollife', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('toollife', 'creator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toollife', sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.execute("UPDATE toollife SET creator_id = user_id")
    op.drop_constraint(None, 'toollife', type_='foreignkey')
    op.create_foreign_key('toollife_creator_id_fkey', 'toollife', 'user', ['creator_id'], ['id'], ondelete='SET NULL')
    op.drop_column('toollife', 'user_id')
    # ### end Alembic commands ###
