"""added number to manufacturer and stop order to tool

Revision ID: ce1c424bfca9
Revises: eaa76bf79378
Create Date: 2025-02-28 10:42:34.167250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ce1c424bfca9'
down_revision: Union[str, None] = 'eaa76bf79378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manufacturer', sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tool', sa.Column('stop_order', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool', 'stop_order')
    op.drop_column('manufacturer', 'number')
    # ### end Alembic commands ###
