"""Made some relationships optional in toolconsumption

Revision ID: daff7ce14839
Revises: 39e3d56e00a1
Create Date: 2025-01-29 10:19:26.523664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daff7ce14839'
down_revision: Union[str, None] = '39e3d56e00a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('toolconsumption', 'machine_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('toolconsumption', 'recipe_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('toolconsumption', 'tool_position_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('toolconsumption', 'workpiece_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('toolconsumption', 'workpiece_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('toolconsumption', 'tool_position_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('toolconsumption', 'recipe_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('toolconsumption', 'machine_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
