"""added last seen to log device and removed track_health

Revision ID: eaa76bf79378
Revises: f0c1619c2a26
Create Date: 2025-02-27 08:07:39.593434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa76bf79378'
down_revision: Union[str, None] = 'f0c1619c2a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logdevice', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.drop_column('logdevice', 'track_health')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logdevice', sa.Column('track_health', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('logdevice', 'last_seen')
    # ### end Alembic commands ###
