"""added a color setting to the line model

Revision ID: ed3ff7938a9d
Revises: 1acd1b671f67
Create Date: 2025-06-23 12:04:55.673283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed3ff7938a9d'
down_revision: Union[str, None] = '1acd1b671f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    color_enum = sa.Enum('RED', 'ORANGE', 'YELLOW', 'LIME', 'GREEN', 'TEAL', 'CYAN', 'BLUE', 'INDIGO', 'VIOLET', 'PINK', 'GRAY', name='color')
    color_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('line', sa.Column('color', color_enum, nullable=False, server_default='GRAY'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line', 'color')
    color_enum = sa.Enum('RED', 'ORANGE', 'YELLOW', 'LIME', 'GREEN', 'TEAL', 'CYAN', 'BLUE', 'INDIGO', 'VIOLET', 'PINK', 'GRAY', name='color')
    color_enum.drop(op.get_bind())
    # ### end Alembic commands ###
