"""added inventory to tool

Revision ID: fa26324c1275
Revises: 50570acd3037
Create Date: 2025-02-18 10:58:55.122303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa26324c1275'
down_revision: Union[str, None] = '50570acd3037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('inventory', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool', 'inventory')
    # ### end Alembic commands ###
