"""added workpiece order completion

Revision ID: fd4a11a939fb
Revises: cef0cfbd1162
Create Date: 2025-01-28 11:54:40.205118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fd4a11a939fb'
down_revision: Union[str, None] = 'cef0cfbd1162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordercompletion',
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('vendor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('batch', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('document_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('workpiece_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workpiece_id'], ['workpiece.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordercompletion_batch'), 'ordercompletion', ['batch'], unique=False)
    op.create_index(op.f('ix_ordercompletion_customer'), 'ordercompletion', ['customer'], unique=False)
    op.create_index(op.f('ix_ordercompletion_date'), 'ordercompletion', ['date'], unique=False)
    op.create_index(op.f('ix_ordercompletion_document_number'), 'ordercompletion', ['document_number'], unique=True)
    op.create_index(op.f('ix_ordercompletion_order'), 'ordercompletion', ['order'], unique=False)
    op.create_index(op.f('ix_ordercompletion_user_id'), 'ordercompletion', ['user_id'], unique=False)
    op.create_index(op.f('ix_ordercompletion_vendor'), 'ordercompletion', ['vendor'], unique=False)
    op.create_index(op.f('ix_ordercompletion_workpiece_id'), 'ordercompletion', ['workpiece_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ordercompletion_workpiece_id'), table_name='ordercompletion')
    op.drop_index(op.f('ix_ordercompletion_vendor'), table_name='ordercompletion')
    op.drop_index(op.f('ix_ordercompletion_user_id'), table_name='ordercompletion')
    op.drop_index(op.f('ix_ordercompletion_order'), table_name='ordercompletion')
    op.drop_index(op.f('ix_ordercompletion_document_number'), table_name='ordercompletion')
    op.drop_index(op.f('ix_ordercompletion_date'), table_name='ordercompletion')
    op.drop_index(op.f('ix_ordercompletion_customer'), table_name='ordercompletion')
    op.drop_index(op.f('ix_ordercompletion_batch'), table_name='ordercompletion')
    op.drop_table('ordercompletion')
    # ### end Alembic commands ###
